version: '2'
services:
    web:
      build: ./web/
      expose:
        - "5000"
      environment:
        - PYTHONPATH=/app/
        - SECRET_KEY=my_super_secret_key
      command: gunicorn ip_task.app:app -c /app/ip_task/etc/gunicorn.conf.py 
      volumes:
        - ./web/ip_task/:/app/ip_task
      depends_on:
        - db

    nginx:
      build: ./nginx/
      ports:
        - "80:80"
      volumes_from:
        - web
      links:
        - web:web

    db:
        build: ./postgresql/
        ports:
         - "5432:5432"
